import React from 'react';
import {
  Home,
  Menu,
  Dashboard,
  ArrowBack,
  ArrowForward,
  Search,
  Edit,
  Delete,
  Add,
  Close,
  Refresh,
  Save,
  Email,
  Phone,
  Notifications,
  Share,
  Star,
  Favorite,
  Download,
  Upload,
  Folder,
  InsertDriveFile,
  Image as ImageIcon,
  AttachFile,
  Person,
  AccountCircle,
  Lock,
  Visibility,
  Settings,
  Help,
  Info,
  Warning,
  Error as ErrorIcon,
  CheckCircle,
  Alarm,
  ContentCopy,

  // Outlined variants
  HomeOutlined,
  MenuOutlined,
  DashboardOutlined,
  ArrowBackOutlined,
  ArrowForwardOutlined,
  SearchOutlined,
  EditOutlined,
  DeleteOutlined,
  AddOutlined,
  CloseOutlined,
  RefreshOutlined,
  SaveOutlined,
  EmailOutlined,
  PhoneOutlined,
  NotificationsOutlined,
  ShareOutlined,
  StarOutlined,
  FavoriteOutlined,
  DownloadOutlined,
  UploadOutlined,
  FolderOutlined,
  InsertDriveFileOutlined,
  ImageOutlined,
  AttachFileOutlined,
  PersonOutlined,
  AccountCircleOutlined,
  LockOutlined,
  VisibilityOutlined,
  SettingsOutlined,
  HelpOutlined,
  InfoOutlined,
  WarningOutlined,
  ErrorOutline,
  CheckCircleOutline,
  AlarmOutlined,
  ContentCopyOutlined,

  // TwoTone variants
  HomeTwoTone,
  MenuTwoTone,
  DashboardTwoTone,
  ArrowBackTwoTone,
  ArrowForwardTwoTone,
  SearchTwoTone,
  EditTwoTone,
  DeleteTwoTone,
  AddTwoTone,
  CloseTwoTone,
  RefreshTwoTone,
  SaveTwoTone,
  EmailTwoTone,
  PhoneTwoTone,
  NotificationsTwoTone,
  ShareTwoTone,
  StarTwoTone,
  FavoriteTwoTone,
  DownloadTwoTone,
  UploadTwoTone,
  FolderTwoTone,
  InsertDriveFileTwoTone,
  ImageTwoTone,
  AttachFileTwoTone,
  PersonTwoTone,
  AccountCircleTwoTone,
  LockTwoTone,
  VisibilityTwoTone,
  SettingsTwoTone,
  HelpTwoTone,
  InfoTwoTone,
  WarningTwoTone,
  ErrorTwoTone,
  CheckCircleTwoTone,
  AlarmTwoTone,
  ContentCopyTwoTone,
} from '@mui/icons-material';

// Filled mapping (base names)
export const materialIconsFilled = {
  'home': Home,
  'menu': Menu,
  'dashboard': Dashboard,
  'arrow-back': ArrowBack,
  'arrow-forward': ArrowForward,
  'search': Search,
  'edit': Edit,
  'delete': Delete,
  'add': Add,
  'close': Close,
  'refresh': Refresh,
  'save': Save,
  'email': Email,
  'phone': Phone,
  'notifications': Notifications,
  'share': Share,
  'star': Star,
  'favorite': Favorite,
  'download': Download,
  'upload': Upload,
  'folder': Folder,
  'insert-drive-file': InsertDriveFile,
  'image': ImageIcon,
  'attach-file': AttachFile,
  'person': Person,
  'account-circle': AccountCircle,
  'lock': Lock,
  'visibility': Visibility,
  'settings': Settings,
  'help': Help,
  'info': Info,
  'warning': Warning,
  'error': ErrorIcon,
  'check-circle': CheckCircle,
  'alarm': Alarm,
  'content-copy': ContentCopy,
} as const;

// Outlined mapping (name-outlined)
export const materialIconsOutlined = {
  'home-outlined': HomeOutlined,
  'menu-outlined': MenuOutlined,
  'dashboard-outlined': DashboardOutlined,
  'arrow-back-outlined': ArrowBackOutlined,
  'arrow-forward-outlined': ArrowForwardOutlined,
  'search-outlined': SearchOutlined,
  'edit-outlined': EditOutlined,
  'delete-outlined': DeleteOutlined,
  'add-outlined': AddOutlined,
  'close-outlined': CloseOutlined,
  'refresh-outlined': RefreshOutlined,
  'save-outlined': SaveOutlined,
  'email-outlined': EmailOutlined,
  'phone-outlined': PhoneOutlined,
  'notifications-outlined': NotificationsOutlined,
  'share-outlined': ShareOutlined,
  'star-outlined': StarOutlined,
  'favorite-outlined': FavoriteOutlined,
  'download-outlined': DownloadOutlined,
  'upload-outlined': UploadOutlined,
  'folder-outlined': FolderOutlined,
  'insert-drive-file-outlined': InsertDriveFileOutlined,
  'image-outlined': ImageOutlined,
  'attach-file-outlined': AttachFileOutlined,
  'person-outlined': PersonOutlined,
  'account-circle-outlined': AccountCircleOutlined,
  'lock-outlined': LockOutlined,
  'visibility-outlined': VisibilityOutlined,
  'settings-outlined': SettingsOutlined,
  'help-outlined': HelpOutlined,
  'info-outlined': InfoOutlined,
  'warning-outlined': WarningOutlined,
  'error-outlined': ErrorOutline,
  'check-circle-outlined': CheckCircleOutline,
  'alarm-outlined': AlarmOutlined,
  'content-copy-outlined': ContentCopyOutlined,
} as const;

// TwoTone mapping (name-two-tone)
export const materialIconsTwoTone = {
  'home-two-tone': HomeTwoTone,
  'menu-two-tone': MenuTwoTone,
  'dashboard-two-tone': DashboardTwoTone,
  'arrow-back-two-tone': ArrowBackTwoTone,
  'arrow-forward-two-tone': ArrowForwardTwoTone,
  'search-two-tone': SearchTwoTone,
  'edit-two-tone': EditTwoTone,
  'delete-two-tone': DeleteTwoTone,
  'add-two-tone': AddTwoTone,
  'close-two-tone': CloseTwoTone,
  'refresh-two-tone': RefreshTwoTone,
  'save-two-tone': SaveTwoTone,
  'email-two-tone': EmailTwoTone,
  'phone-two-tone': PhoneTwoTone,
  'notifications-two-tone': NotificationsTwoTone,
  'share-two-tone': ShareTwoTone,
  'star-two-tone': StarTwoTone,
  'favorite-two-tone': FavoriteTwoTone,
  'download-two-tone': DownloadTwoTone,
  'upload-two-tone': UploadTwoTone,
  'folder-two-tone': FolderTwoTone,
  'insert-drive-file-two-tone': InsertDriveFileTwoTone,
  'image-two-tone': ImageTwoTone,
  'attach-file-two-tone': AttachFileTwoTone,
  'person-two-tone': PersonTwoTone,
  'account-circle-two-tone': AccountCircleTwoTone,
  'lock-two-tone': LockTwoTone,
  'visibility-two-tone': VisibilityTwoTone,
  'settings-two-tone': SettingsTwoTone,
  'help-two-tone': HelpTwoTone,
  'info-two-tone': InfoTwoTone,
  'warning-two-tone': WarningTwoTone,
  'error-two-tone': ErrorTwoTone,
  'check-circle-two-tone': CheckCircleTwoTone,
  'alarm-two-tone': AlarmTwoTone,
  'content-copy-two-tone': ContentCopyTwoTone,
} as const;

export type MaterialIconFilledName = keyof typeof materialIconsFilled;
export type MaterialIconOutlinedName = keyof typeof materialIconsOutlined;
export type MaterialIconTwoToneName = keyof typeof materialIconsTwoTone;
export type AllMaterialIconName =
  | MaterialIconFilledName
  | MaterialIconOutlinedName
  | MaterialIconTwoToneName;
