import React from 'react';
import {
  // Navigation & Layout
  Home,
  Menu,
  Dashboard,
  ArrowBack,
  ArrowForward,
  ArrowUpward,
  ArrowDownward,
  ExpandMore,
  ExpandLess,
  Directions,
  Map,
  Place,
  LocationOn,

  // Actions & Controls
  Search,
  Edit,
  Delete,
  Add,
  Remove,
  Close,
  Refresh,
  Save,
  Download,
  Upload,
  Share,
  Print,
  Build,
  Settings,
  Check,
  MoreVert,
  MoreHoriz,
  FilterList,
  Sort,
  GetApp,
  Clear,

  // Communication
  Email,
  Phone,
  Notifications,
  Chat,
  Comment,
  Forum,
  Send,
  Inbox,
  Drafts,
  MarkEmailRead,
  Unsubscribe,

  // Social & Feedback
  ThumbUp,
  ThumbDown,
  Star,
  Favorite,
  Bookmark,
  TrendingUp,

  // Content & Media
  History,
  Assignment,
  Description,
  List,
  ViewList,
  ViewModule,
  GridView,
  TableChart,
  Folder,
  InsertDriveFile,
  Image as ImageIcon,
  Photo,
  PhotoLibrary,
  Collections,
  VideoLibrary,
  MusicNote,
  AttachFile,
  CloudUpload,
  CloudDownload,

  // User & Account
  Person,
  AccountCircle,
  AccountBox,
  Group,
  Work,
  ExitToApp,
  Lock,
  LockOpen,
  Visibility,
  VisibilityOff,
  Security,
  Shield,
  Verified,

  // System & Status
  Info,
  Warning,
  Error as ErrorIcon,
  CheckCircle,
  Help,
  BugReport,
  Code,

  // Time & Calendar
  CalendarToday,
  Schedule,
  Alarm,

  // Analytics & Charts
  BarChart,
  PieChart,
  Timeline,

  // Commerce
  ShoppingCart,
  Payment,

  // Network & Connectivity
  Language,
  Public,
  Wifi,
  Bluetooth,
  BatteryFull,
  SignalCellularAlt,

  // Media Controls
  PlayArrow,
  Pause,
  Stop,
  SkipNext,
  SkipPrevious,
  VolumeUp,
  VolumeOff,
  Mic,
  MicOff,
  Videocam,
  VideocamOff,
  CameraAlt,

  // Design & Creative
  ColorLens,
  Palette,
  Brush,
  FormatPaint,
  ContentCopy,

  // Outlined variants
  HomeOutlined,
  MenuOutlined,
  DashboardOutlined,
  ArrowBackOutlined,
  ArrowForwardOutlined,
  ArrowUpwardOutlined,
  ArrowDownwardOutlined,
  ExpandMoreOutlined,
  ExpandLessOutlined,
  DirectionsOutlined,
  MapOutlined,
  PlaceOutlined,
  LocationOnOutlined,
  SearchOutlined,
  EditOutlined,
  DeleteOutlined,
  AddOutlined,
  RemoveOutlined,
  CloseOutlined,
  RefreshOutlined,
  SaveOutlined,
  DownloadOutlined,
  UploadOutlined,
  ShareOutlined,
  PrintOutlined,
  BuildOutlined,
  SettingsOutlined,
  CheckOutlined,
  MoreVertOutlined,
  MoreHorizOutlined,
  FilterListOutlined,
  SortOutlined,
  GetAppOutlined,
  ClearOutlined,
  EmailOutlined,
  PhoneOutlined,
  NotificationsOutlined,
  ChatOutlined,
  CommentOutlined,
  ForumOutlined,
  SendOutlined,
  InboxOutlined,
  DraftsOutlined,
  MarkEmailReadOutlined,
  UnsubscribeOutlined,
  ThumbUpOutlined,
  ThumbDownOutlined,
  StarOutlined,
  FavoriteOutlined,
  BookmarkOutlined,
  TrendingUpOutlined,
  HistoryOutlined,
  AssignmentOutlined,
  DescriptionOutlined,
  ListOutlined,
  ViewListOutlined,
  ViewModuleOutlined,
  GridViewOutlined,
  TableChartOutlined,
  FolderOutlined,
  InsertDriveFileOutlined,
  ImageOutlined,
  PhotoOutlined,
  PhotoLibraryOutlined,
  CollectionsOutlined,
  VideoLibraryOutlined,
  MusicNoteOutlined,
  AttachFileOutlined,
  CloudUploadOutlined,
  CloudDownloadOutlined,
  PersonOutlined,
  AccountCircleOutlined,
  AccountBoxOutlined,
  GroupOutlined,
  WorkOutlined,
  ExitToAppOutlined,
  LockOutlined,
  LockOpenOutlined,
  VisibilityOutlined,
  VisibilityOffOutlined,
  SecurityOutlined,
  ShieldOutlined,
  VerifiedOutlined,
  InfoOutlined,
  WarningOutlined,
  ErrorOutline,
  CheckCircleOutline,
  HelpOutlined,
  BugReportOutlined,
  CodeOutlined,
  CalendarTodayOutlined,
  ScheduleOutlined,
  AlarmOutlined,
  BarChartOutlined,
  PieChartOutlined,
  TimelineOutlined,
  ShoppingCartOutlined,
  PaymentOutlined,
  LanguageOutlined,
  PublicOutlined,
  WifiOutlined,
  BluetoothOutlined,
  BatteryFullOutlined,
  SignalCellularAltOutlined,
  PlayArrowOutlined,
  PauseOutlined,
  StopOutlined,
  SkipNextOutlined,
  SkipPreviousOutlined,
  VolumeUpOutlined,
  VolumeOffOutlined,
  MicOutlined,
  MicOffOutlined,
  VideocamOutlined,
  VideocamOffOutlined,
  CameraAltOutlined,
  ColorLensOutlined,
  PaletteOutlined,
  BrushOutlined,
  FormatPaintOutlined,
  ContentCopyOutlined,

  // TwoTone variants
  HomeTwoTone,
  MenuTwoTone,
  DashboardTwoTone,
  ArrowBackTwoTone,
  ArrowForwardTwoTone,
  ArrowUpwardTwoTone,
  ArrowDownwardTwoTone,
  ExpandMoreTwoTone,
  ExpandLessTwoTone,
  DirectionsTwoTone,
  MapTwoTone,
  PlaceTwoTone,
  LocationOnTwoTone,
  SearchTwoTone,
  EditTwoTone,
  DeleteTwoTone,
  AddTwoTone,
  RemoveTwoTone,
  CloseTwoTone,
  RefreshTwoTone,
  SaveTwoTone,
  DownloadTwoTone,
  UploadTwoTone,
  ShareTwoTone,
  PrintTwoTone,
  BuildTwoTone,
  SettingsTwoTone,
  CheckTwoTone,
  MoreVertTwoTone,
  MoreHorizTwoTone,
  FilterListTwoTone,
  SortTwoTone,
  GetAppTwoTone,
  ClearTwoTone,
  EmailTwoTone,
  PhoneTwoTone,
  NotificationsTwoTone,
  ChatTwoTone,
  CommentTwoTone,
  ForumTwoTone,
  SendTwoTone,
  InboxTwoTone,
  DraftsTwoTone,
  MarkEmailReadTwoTone,
  UnsubscribeTwoTone,
  ThumbUpTwoTone,
  ThumbDownTwoTone,
  StarTwoTone,
  FavoriteTwoTone,
  BookmarkTwoTone,
  TrendingUpTwoTone,
  HistoryTwoTone,
  AssignmentTwoTone,
  DescriptionTwoTone,
  ListTwoTone,
  ViewListTwoTone,
  ViewModuleTwoTone,
  GridViewTwoTone,
  TableChartTwoTone,
  FolderTwoTone,
  InsertDriveFileTwoTone,
  ImageTwoTone,
  PhotoTwoTone,
  PhotoLibraryTwoTone,
  CollectionsTwoTone,
  VideoLibraryTwoTone,
  MusicNoteTwoTone,
  AttachFileTwoTone,
  CloudUploadTwoTone,
  CloudDownloadTwoTone,
  PersonTwoTone,
  AccountCircleTwoTone,
  AccountBoxTwoTone,
  GroupTwoTone,
  WorkTwoTone,
  ExitToAppTwoTone,
  LockTwoTone,
  LockOpenTwoTone,
  VisibilityTwoTone,
  VisibilityOffTwoTone,
  SecurityTwoTone,
  ShieldTwoTone,
  VerifiedTwoTone,
  InfoTwoTone,
  WarningTwoTone,
  ErrorTwoTone,
  CheckCircleTwoTone,
  HelpTwoTone,
  BugReportTwoTone,
  CodeTwoTone,
  CalendarTodayTwoTone,
  ScheduleTwoTone,
  AlarmTwoTone,
  BarChartTwoTone,
  PieChartTwoTone,
  TimelineTwoTone,
  ShoppingCartTwoTone,
  PaymentTwoTone,
  LanguageTwoTone,
  PublicTwoTone,
  WifiTwoTone,
  BluetoothTwoTone,
  BatteryFullTwoTone,
  SignalCellularAltTwoTone,
  PlayArrowTwoTone,
  PauseTwoTone,
  StopTwoTone,
  SkipNextTwoTone,
  SkipPreviousTwoTone,
  VolumeUpTwoTone,
  VolumeOffTwoTone,
  MicTwoTone,
  MicOffTwoTone,
  VideocamTwoTone,
  VideocamOffTwoTone,
  CameraAltTwoTone,
  ColorLensTwoTone,
  PaletteTwoTone,
  BrushTwoTone,
  FormatPaintTwoTone,
  ContentCopyTwoTone,
} from '@mui/icons-material';

// Filled mapping (base names)
export const materialIconsFilled = {
  // Navigation & Layout
  'home': Home,
  'menu': Menu,
  'dashboard': Dashboard,
  'arrow-back': ArrowBack,
  'arrow-forward': ArrowForward,
  'arrow-upward': ArrowUpward,
  'arrow-downward': ArrowDownward,
  'expand-more': ExpandMore,
  'expand-less': ExpandLess,
  'directions': Directions,
  'map': Map,
  'place': Place,
  'location-on': LocationOn,

  // Actions & Controls
  'search': Search,
  'edit': Edit,
  'delete': Delete,
  'add': Add,
  'remove': Remove,
  'close': Close,
  'refresh': Refresh,
  'save': Save,
  'download': Download,
  'upload': Upload,
  'share': Share,
  'print': Print,
  'build': Build,
  'settings': Settings,
  'check': Check,
  'more-vert': MoreVert,
  'more-horiz': MoreHoriz,
  'filter-list': FilterList,
  'sort': Sort,
  'get-app': GetApp,
  'clear': Clear,

  // Communication
  'email': Email,
  'phone': Phone,
  'notifications': Notifications,
  'chat': Chat,
  'comment': Comment,
  'forum': Forum,
  'send': Send,
  'inbox': Inbox,
  'drafts': Drafts,
  'mark-email-read': MarkEmailRead,
  'unsubscribe': Unsubscribe,

  // Social & Feedback
  'thumb-up': ThumbUp,
  'thumb-down': ThumbDown,
  'star': Star,
  'favorite': Favorite,
  'bookmark': Bookmark,
  'trending-up': TrendingUp,

  // Content & Media
  'history': History,
  'assignment': Assignment,
  'description': Description,
  'list': List,
  'view-list': ViewList,
  'view-module': ViewModule,
  'grid-view': GridView,
  'table-chart': TableChart,
  'folder': Folder,
  'insert-drive-file': InsertDriveFile,
  'image': ImageIcon,
  'photo': Photo,
  'photo-library': PhotoLibrary,
  'collections': Collections,
  'video-library': VideoLibrary,
  'music-note': MusicNote,
  'attach-file': AttachFile,
  'cloud-upload': CloudUpload,
  'cloud-download': CloudDownload,

  // User & Account
  'person': Person,
  'account-circle': AccountCircle,
  'account-box': AccountBox,
  'group': Group,
  'work': Work,
  'exit-to-app': ExitToApp,
  'lock': Lock,
  'lock-open': LockOpen,
  'visibility': Visibility,
  'visibility-off': VisibilityOff,
  'security': Security,
  'shield': Shield,
  'verified': Verified,

  // System & Status
  'info': Info,
  'warning': Warning,
  'error': ErrorIcon,
  'check-circle': CheckCircle,
  'help': Help,
  'bug-report': BugReport,
  'code': Code,

  // Time & Calendar
  'calendar-today': CalendarToday,
  'schedule': Schedule,
  'alarm': Alarm,

  // Analytics & Charts
  'bar-chart': BarChart,
  'pie-chart': PieChart,
  'timeline': Timeline,

  // Commerce
  'shopping-cart': ShoppingCart,
  'payment': Payment,

  // Network & Connectivity
  'language': Language,
  'public': Public,
  'wifi': Wifi,
  'bluetooth': Bluetooth,
  'battery-full': BatteryFull,
  'signal-cellular-alt': SignalCellularAlt,

  // Media Controls
  'play-arrow': PlayArrow,
  'pause': Pause,
  'stop': Stop,
  'skip-next': SkipNext,
  'skip-previous': SkipPrevious,
  'volume-up': VolumeUp,
  'volume-off': VolumeOff,
  'mic': Mic,
  'mic-off': MicOff,
  'videocam': Videocam,
  'videocam-off': VideocamOff,
  'camera-alt': CameraAlt,

  // Design & Creative
  'color-lens': ColorLens,
  'palette': Palette,
  'brush': Brush,
  'format-paint': FormatPaint,
  'content-copy': ContentCopy,
} as const;

// Outlined mapping (name-outlined)
export const materialIconsOutlined = {
  // Navigation & Layout
  'home-outlined': HomeOutlined,
  'menu-outlined': MenuOutlined,
  'dashboard-outlined': DashboardOutlined,
  'arrow-back-outlined': ArrowBackOutlined,
  'arrow-forward-outlined': ArrowForwardOutlined,
  'arrow-upward-outlined': ArrowUpwardOutlined,
  'arrow-downward-outlined': ArrowDownwardOutlined,
  'expand-more-outlined': ExpandMoreOutlined,
  'expand-less-outlined': ExpandLessOutlined,
  'directions-outlined': DirectionsOutlined,
  'map-outlined': MapOutlined,
  'place-outlined': PlaceOutlined,
  'location-on-outlined': LocationOnOutlined,

  // Actions & Controls
  'search-outlined': SearchOutlined,
  'edit-outlined': EditOutlined,
  'delete-outlined': DeleteOutlined,
  'add-outlined': AddOutlined,
  'remove-outlined': RemoveOutlined,
  'close-outlined': CloseOutlined,
  'refresh-outlined': RefreshOutlined,
  'save-outlined': SaveOutlined,
  'download-outlined': DownloadOutlined,
  'upload-outlined': UploadOutlined,
  'share-outlined': ShareOutlined,
  'print-outlined': PrintOutlined,
  'build-outlined': BuildOutlined,
  'settings-outlined': SettingsOutlined,
  'check-outlined': CheckOutlined,
  'more-vert-outlined': MoreVertOutlined,
  'more-horiz-outlined': MoreHorizOutlined,
  'filter-list-outlined': FilterListOutlined,
  'sort-outlined': SortOutlined,
  'get-app-outlined': GetAppOutlined,
  'clear-outlined': ClearOutlined,

  // Communication
  'email-outlined': EmailOutlined,
  'phone-outlined': PhoneOutlined,
  'notifications-outlined': NotificationsOutlined,
  'chat-outlined': ChatOutlined,
  'comment-outlined': CommentOutlined,
  'forum-outlined': ForumOutlined,
  'send-outlined': SendOutlined,
  'inbox-outlined': InboxOutlined,
  'drafts-outlined': DraftsOutlined,
  'mark-email-read-outlined': MarkEmailReadOutlined,
  'unsubscribe-outlined': UnsubscribeOutlined,

  // Social & Feedback
  'thumb-up-outlined': ThumbUpOutlined,
  'thumb-down-outlined': ThumbDownOutlined,
  'star-outlined': StarOutlined,
  'favorite-outlined': FavoriteOutlined,
  'bookmark-outlined': BookmarkOutlined,
  'trending-up-outlined': TrendingUpOutlined,

  // Content & Media
  'history-outlined': HistoryOutlined,
  'assignment-outlined': AssignmentOutlined,
  'description-outlined': DescriptionOutlined,
  'list-outlined': ListOutlined,
  'view-list-outlined': ViewListOutlined,
  'view-module-outlined': ViewModuleOutlined,
  'grid-view-outlined': GridViewOutlined,
  'table-chart-outlined': TableChartOutlined,
  'folder-outlined': FolderOutlined,
  'insert-drive-file-outlined': InsertDriveFileOutlined,
  'image-outlined': ImageOutlined,
  'photo-outlined': PhotoOutlined,
  'photo-library-outlined': PhotoLibraryOutlined,
  'collections-outlined': CollectionsOutlined,
  'video-library-outlined': VideoLibraryOutlined,
  'music-note-outlined': MusicNoteOutlined,
  'attach-file-outlined': AttachFileOutlined,
  'cloud-upload-outlined': CloudUploadOutlined,
  'cloud-download-outlined': CloudDownloadOutlined,

  // User & Account
  'person-outlined': PersonOutlined,
  'account-circle-outlined': AccountCircleOutlined,
  'account-box-outlined': AccountBoxOutlined,
  'group-outlined': GroupOutlined,
  'work-outlined': WorkOutlined,
  'exit-to-app-outlined': ExitToAppOutlined,
  'lock-outlined': LockOutlined,
  'lock-open-outlined': LockOpenOutlined,
  'visibility-outlined': VisibilityOutlined,
  'visibility-off-outlined': VisibilityOffOutlined,
  'security-outlined': SecurityOutlined,
  'shield-outlined': ShieldOutlined,
  'verified-outlined': VerifiedOutlined,

  // System & Status
  'info-outlined': InfoOutlined,
  'warning-outlined': WarningOutlined,
  'error-outlined': ErrorOutline,
  'check-circle-outlined': CheckCircleOutline,
  'help-outlined': HelpOutlined,
  'bug-report-outlined': BugReportOutlined,
  'code-outlined': CodeOutlined,

  // Time & Calendar
  'calendar-today-outlined': CalendarTodayOutlined,
  'schedule-outlined': ScheduleOutlined,
  'alarm-outlined': AlarmOutlined,

  // Analytics & Charts
  'bar-chart-outlined': BarChartOutlined,
  'pie-chart-outlined': PieChartOutlined,
  'timeline-outlined': TimelineOutlined,

  // Commerce
  'shopping-cart-outlined': ShoppingCartOutlined,
  'payment-outlined': PaymentOutlined,

  // Network & Connectivity
  'language-outlined': LanguageOutlined,
  'public-outlined': PublicOutlined,
  'wifi-outlined': WifiOutlined,
  'bluetooth-outlined': BluetoothOutlined,
  'battery-full-outlined': BatteryFullOutlined,
  'signal-cellular-alt-outlined': SignalCellularAltOutlined,

  // Media Controls
  'play-arrow-outlined': PlayArrowOutlined,
  'pause-outlined': PauseOutlined,
  'stop-outlined': StopOutlined,
  'skip-next-outlined': SkipNextOutlined,
  'skip-previous-outlined': SkipPreviousOutlined,
  'volume-up-outlined': VolumeUpOutlined,
  'volume-off-outlined': VolumeOffOutlined,
  'mic-outlined': MicOutlined,
  'mic-off-outlined': MicOffOutlined,
  'videocam-outlined': VideocamOutlined,
  'videocam-off-outlined': VideocamOffOutlined,
  'camera-alt-outlined': CameraAltOutlined,

  // Design & Creative
  'color-lens-outlined': ColorLensOutlined,
  'palette-outlined': PaletteOutlined,
  'brush-outlined': BrushOutlined,
  'format-paint-outlined': FormatPaintOutlined,
  'content-copy-outlined': ContentCopyOutlined,
} as const;

// TwoTone mapping (name-two-tone)
export const materialIconsTwoTone = {
  // Navigation & Layout
  'home-two-tone': HomeTwoTone,
  'menu-two-tone': MenuTwoTone,
  'dashboard-two-tone': DashboardTwoTone,
  'arrow-back-two-tone': ArrowBackTwoTone,
  'arrow-forward-two-tone': ArrowForwardTwoTone,
  'arrow-upward-two-tone': ArrowUpwardTwoTone,
  'arrow-downward-two-tone': ArrowDownwardTwoTone,
  'expand-more-two-tone': ExpandMoreTwoTone,
  'expand-less-two-tone': ExpandLessTwoTone,
  'directions-two-tone': DirectionsTwoTone,
  'map-two-tone': MapTwoTone,
  'place-two-tone': PlaceTwoTone,
  'location-on-two-tone': LocationOnTwoTone,

  // Actions & Controls
  'search-two-tone': SearchTwoTone,
  'edit-two-tone': EditTwoTone,
  'delete-two-tone': DeleteTwoTone,
  'add-two-tone': AddTwoTone,
  'remove-two-tone': RemoveTwoTone,
  'close-two-tone': CloseTwoTone,
  'refresh-two-tone': RefreshTwoTone,
  'save-two-tone': SaveTwoTone,
  'download-two-tone': DownloadTwoTone,
  'upload-two-tone': UploadTwoTone,
  'share-two-tone': ShareTwoTone,
  'print-two-tone': PrintTwoTone,
  'build-two-tone': BuildTwoTone,
  'settings-two-tone': SettingsTwoTone,
  'check-two-tone': CheckTwoTone,
  'more-vert-two-tone': MoreVertTwoTone,
  'more-horiz-two-tone': MoreHorizTwoTone,
  'filter-list-two-tone': FilterListTwoTone,
  'sort-two-tone': SortTwoTone,
  'get-app-two-tone': GetAppTwoTone,
  'clear-two-tone': ClearTwoTone,

  // Communication
  'email-two-tone': EmailTwoTone,
  'phone-two-tone': PhoneTwoTone,
  'notifications-two-tone': NotificationsTwoTone,
  'chat-two-tone': ChatTwoTone,
  'comment-two-tone': CommentTwoTone,
  'forum-two-tone': ForumTwoTone,
  'send-two-tone': SendTwoTone,
  'inbox-two-tone': InboxTwoTone,
  'drafts-two-tone': DraftsTwoTone,
  'mark-email-read-two-tone': MarkEmailReadTwoTone,
  'unsubscribe-two-tone': UnsubscribeTwoTone,

  // Social & Feedback
  'thumb-up-two-tone': ThumbUpTwoTone,
  'thumb-down-two-tone': ThumbDownTwoTone,
  'star-two-tone': StarTwoTone,
  'favorite-two-tone': FavoriteTwoTone,
  'bookmark-two-tone': BookmarkTwoTone,
  'trending-up-two-tone': TrendingUpTwoTone,

  // Content & Media
  'history-two-tone': HistoryTwoTone,
  'assignment-two-tone': AssignmentTwoTone,
  'description-two-tone': DescriptionTwoTone,
  'list-two-tone': ListTwoTone,
  'view-list-two-tone': ViewListTwoTone,
  'view-module-two-tone': ViewModuleTwoTone,
  'grid-view-two-tone': GridViewTwoTone,
  'table-chart-two-tone': TableChartTwoTone,
  'folder-two-tone': FolderTwoTone,
  'insert-drive-file-two-tone': InsertDriveFileTwoTone,
  'image-two-tone': ImageTwoTone,
  'photo-two-tone': PhotoTwoTone,
  'photo-library-two-tone': PhotoLibraryTwoTone,
  'collections-two-tone': CollectionsTwoTone,
  'video-library-two-tone': VideoLibraryTwoTone,
  'music-note-two-tone': MusicNoteTwoTone,
  'attach-file-two-tone': AttachFileTwoTone,
  'cloud-upload-two-tone': CloudUploadTwoTone,
  'cloud-download-two-tone': CloudDownloadTwoTone,

  // User & Account
  'person-two-tone': PersonTwoTone,
  'account-circle-two-tone': AccountCircleTwoTone,
  'account-box-two-tone': AccountBoxTwoTone,
  'group-two-tone': GroupTwoTone,
  'work-two-tone': WorkTwoTone,
  'exit-to-app-two-tone': ExitToAppTwoTone,
  'lock-two-tone': LockTwoTone,
  'lock-open-two-tone': LockOpenTwoTone,
  'visibility-two-tone': VisibilityTwoTone,
  'visibility-off-two-tone': VisibilityOffTwoTone,
  'security-two-tone': SecurityTwoTone,
  'shield-two-tone': ShieldTwoTone,
  'verified-two-tone': VerifiedTwoTone,

  // System & Status
  'info-two-tone': InfoTwoTone,
  'warning-two-tone': WarningTwoTone,
  'error-two-tone': ErrorTwoTone,
  'check-circle-two-tone': CheckCircleTwoTone,
  'help-two-tone': HelpTwoTone,
  'bug-report-two-tone': BugReportTwoTone,
  'code-two-tone': CodeTwoTone,

  // Time & Calendar
  'calendar-today-two-tone': CalendarTodayTwoTone,
  'schedule-two-tone': ScheduleTwoTone,
  'alarm-two-tone': AlarmTwoTone,

  // Analytics & Charts
  'bar-chart-two-tone': BarChartTwoTone,
  'pie-chart-two-tone': PieChartTwoTone,
  'timeline-two-tone': TimelineTwoTone,

  // Commerce
  'shopping-cart-two-tone': ShoppingCartTwoTone,
  'payment-two-tone': PaymentTwoTone,

  // Network & Connectivity
  'language-two-tone': LanguageTwoTone,
  'public-two-tone': PublicTwoTone,
  'wifi-two-tone': WifiTwoTone,
  'bluetooth-two-tone': BluetoothTwoTone,
  'battery-full-two-tone': BatteryFullTwoTone,
  'signal-cellular-alt-two-tone': SignalCellularAltTwoTone,

  // Media Controls
  'play-arrow-two-tone': PlayArrowTwoTone,
  'pause-two-tone': PauseTwoTone,
  'stop-two-tone': StopTwoTone,
  'skip-next-two-tone': SkipNextTwoTone,
  'skip-previous-two-tone': SkipPreviousTwoTone,
  'volume-up-two-tone': VolumeUpTwoTone,
  'volume-off-two-tone': VolumeOffTwoTone,
  'mic-two-tone': MicTwoTone,
  'mic-off-two-tone': MicOffTwoTone,
  'videocam-two-tone': VideocamTwoTone,
  'videocam-off-two-tone': VideocamOffTwoTone,
  'camera-alt-two-tone': CameraAltTwoTone,

  // Design & Creative
  'color-lens-two-tone': ColorLensTwoTone,
  'palette-two-tone': PaletteTwoTone,
  'brush-two-tone': BrushTwoTone,
  'format-paint-two-tone': FormatPaintTwoTone,
  'content-copy-two-tone': ContentCopyTwoTone,
} as const;

export type MaterialIconFilledName = keyof typeof materialIconsFilled;
export type MaterialIconOutlinedName = keyof typeof materialIconsOutlined;
export type MaterialIconTwoToneName = keyof typeof materialIconsTwoTone;
export type AllMaterialIconName =
  | MaterialIconFilledName
  | MaterialIconOutlinedName
  | MaterialIconTwoToneName;
